<template>
  <div class="detect-type-show">
    <window-card title="All Type Of Trash">
      <div class="type-images">
        <el-popover
          v-for="config in trashTypeConfigs"
          :key="config.id"
          :placement="config.placement"
          width="200"
          trigger="click"
        >
          <h3 style="text-align: center">{{ config.name }}</h3>
          <p
            :style="{
              wordBreak: 'normal',
              textAlign: 'center',
              hyphens: 'auto'
            }"
          >
            {{ config.about }}
          </p>
          <img slot="reference" :src="config.imgSrc" alt="" />
        </el-popover>
      </div>
    </window-card>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'

interface trashTypeConfig {
  imgSrc: string
  name: string
  about: string
  id: number
  // for tootip place
  placement: string
}

@Component({})
export default class DetectTypeShow extends Vue {
  static _trashTypeConfigs: trashTypeConfig[] = [
    {
      name: 'Recyclable Waste',
      imgSrc: require('@/assets/recy.jpg'),
      about:
        'Waste paper, waste plastics, waste glass products, scrap metal, waste fabrics, etc. Domestic waste suitable for recycling',
      placement: 'top-start',
      id: 1
    },
    {
      name: 'Residual Waste',
      imgSrc: require('@/assets/residual.jpg'),
      about:
        'Domestic waste other than recyclable garbage, hazardous waste, and wet garbage',
      placement: 'bottom',
      id: 2
    },
    {
      name: 'Household Waste',
      imgSrc: require('@/assets/household.jpg'),
      about: 'Perishable biomass waste generated by household garbage',
      placement: 'top',
      id: 3
    },
    {
      name: 'Hazardous Waste',
      imgSrc: require('@/assets/harm.jpg'),
      about:
        'Waste batteries, waste lamps, waste drugs, waste paint and their containers are domestic wastes that cause direct or potential harm to human health or the natural environment.',
      placement: 'right',
      id: 4
    }
  ]

  get trashTypeConfigs() {
    return DetectTypeShow._trashTypeConfigs
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.detect-type-show {
  margin-top: 1rem;
  h3 {
    text-align: center;
  }
}

.type-images {
  display: flex;
  justify-content: space-around;
  img {
    width: 7rem;
    transition: all 0.5s ease;

    &:hover {
      opacity: 0.8;
      cursor: pointer;
    }
  }
}
</style>
