query List($trashQueryList: [TrashQueryArg!]!) {
  trashList(trashNameList: $trashQueryList) {
    id
    name
    type {
      id
      name
    }
    extraInfo {
      id
      degrateTime
      degrateWay
      about
      category
    }
  }
}
