mutation uploadImageByURL($imgURL: String) {
  uploadImageByURL(imgURL: $imgURL) {
    taggedImageResult {
      keyword
      score
      root
    }
    taggedImagePosition {
      width
      height
      top
      left
    }
  }
}
